apiVersion: v1
kind: DeploymentConfig
metadata:
  name: node-web-app
  labels:
    app: node-web-app
spec:
  replicas: 2
  selector:
    app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
      - image: docker-registry.default.svc:5000/myproj1/node-web-app:latest
        imagePullPolicy: Always
        name: node-web-app
      dnsPolicy: ClusterFirst
      restartPolicy: Always
